#!/bin/sh

./mvnw checkstyle:check

RESULTS=$?

if [ $RESULTS -ne 0 ]; then
  BG="\033[43m"
  TX="\033[1;30m"
  LE="\033[0m"

  printf "\n\n\n"
  echo "${BG}${TX}                                                                                        ${LE}"
  echo "${BG}${TX}                        ☠️  체크스타일 규칙을 준수해주세요 !                            ${LE}" 
  echo "${BG}${TX}                                                                                        ${LE} "
  printf "\n\n\n"

  exit 1
fi

printf "\033[1m\033[35m \n\n\nThanks for keep the codestyle ❤️\n\n\n"
exit 0
